- name: >
    Download OneAgent installer and install OneAgent on Windows machines
  hosts: all
  vars:
    oneagent_paas_token: "{{ dynatrace_token }}"
    oneagent_environment_url: "{{ dynatrace_url }}"
    oneagent_install_args:
      - INSTALL_PATH=/opt/example
      - GROUP=example_group
      - --set-host-name="{{ inventory_hostname }}"
      - --set-host-tag=windows
  tasks:
    - name: Get Dynatrace App
      ansible.builtin.get_url:
        url: "{{ oneagent_environment_url }}/api/v1/deployment/installer/agent/windows/default/latest"
        dest: C:\Temp\Dynatrace-OneAgent-Windows.exe
        mode: '0755'
        headers:
          Authorization: "Api-Token {{ dynatrace_token }}"
    
    - name: Import Dynatrace OneAgent role
      ansible.builtin.import_role:
        name: dynatrace.oneagent.oneagent