- name: >
    Download OneAgent installer and install OneAgent on Windows machines
  hosts: all
  
  roles:
    - role: dynatrace.oneagent.oneagent
      vars:
        oneagent_paas_token: "{{ dynatrace_token }}"
        oneagent_environment_url: "{{ dynatrace_url }}"
        package_state: "{{ dynatrace_package_state | default('present') }}"
      when: dynatrace_package_state is defined