---
- name: Install IIS
  hosts: all
  vars:
    iis_message: undef

  tasks:
    - name: Install IIS
      ansible.windows.win_feature:
        name: Web-Server
        state: present

    - name: Start IIS service
      ansible.windows.win_service:
        name: W3Svc
        state: started

    - name: Create website index.html
      ansible.windows.win_copy:
        src: "hello.html"
        dest: C:\Inetpub\wwwroot\index.html
    
    - name: Copy images
      ansible.windows.win_copy:
        src: "hayden.jpg"
        dest: C:\Inetpub\wwwroot\hayden.jpg

    - name: Show website address
      ansible.builtin.debug:
        msg: http://{{ ansible_host }}
