---
- name: Join Active Directory domain
  hosts: all
  gather_facts: false

  tasks:
    - name: Extract domain controller private ip
      ansible.builtin.set_fact:
        domain_controller_private_ip: "{{ hostvars[groups['purpose_domain_controller'][0]]['private_ip_address'] }}"

    - name: Join AD Domain
      when: domain_join_name is defined
      block:

        - name: Set Domain Facts
          ansible.builtin.set_fact:
            domain_ou: "{{ domain_join_name.split('.') }}"

        - name: Set a single address on the adapter named Ethernet
          ansible.windows.win_dns_client:
            adapter_names: 'Ethernet*'
            dns_servers: 
              - "{{ domain_controller_private_ip }}"
              - 1.1.1.1

        - name: Update the hostname
          ansible.windows.win_hostname:
            name: "{{ inventory_hostname }}"

        - name: Join domain
          register: r_domain_membership
          microsoft.ad.membership:
            dns_domain_name: "{{ domain_join_name }}"
            hostname: "{{ inventory_hostname }}"
            domain_admin_user: "{{ ansible_user }}@{{ domain_join_name }}"
            domain_admin_password: "{{ ansible_password }}"
            domain_ou_path: "OU=Demo,DC={{ domain_ou.0 }},DC={{ domain_ou.1 }}"
            state: domain
          failed_when: false

        - name: Reboot windows machine
          when: reboot_server is defined
          ansible.windows.win_reboot:
