---
- name: Windows updates
  hosts: all
  vars:
    report_server: web4

  tasks:
    - name: Patch windows server
      ansible.builtin.include_role:
        name: demo.patching.patch_windows

    - name: Build report server
      ansible.builtin.include_role:
        name: demo.patching.report_windows_patching        

    - name: Send report to Mattermost 
      community.general.mattermost:
        url: "{{ mattermost_url}}"
        api_key: "{{ mattermost_token }}"
        channel: device-info
        text: "Windows patching report for {{ inventory_hostname }}"
        attachments:
          - C:\Temp\windowspatch.html