---
- name: Windows updates
  hosts: all
  vars:
    report_server: web4

  tasks:
    - name: Patch windows server
      ansible.builtin.include_role:
        name: demo.patching.patch_windows

    - name: Build report server
      ansible.builtin.include_role:
        name: demo.patching.report_windows_patching      

    - name: Fetch report
      ansible.builtin.fetch:
        src: "C:\Temp\windowspatch.html"
        dest: "/tmp/{{ inventory_hostname }}_windowspatch.html"
        flat: yes
      delegate_to: "{{ inventory_hostname }}"

    - name: Send report to Mattermost 
      community.general.mattermost:
        url: "{{ mattermost_url}}"
        api_key: "{{ mattermost_token }}"
        channel: device-info
        text: "Windows patching report for {{ inventory_hostname }}"
        attachments:
          - "/tmp/{{ inventory_hostname }}_windowspatch.html"