---
- name: Windows updates
  hosts: all
  vars:
    report_server: web4

  tasks:

    - name: Create Temp Directory
      ansible.windows.win_file:
        path: C:\Temp
        state: directory

    - name: Patch windows server
      ansible.builtin.include_role:
        name: demo.patching.patch_windows

    - name: Build report server
      ansible.builtin.include_role:
        name: demo.patching.report_windows_patching      

    - name: Fetch report
      ansible.builtin.fetch:
        src: "C:\\Temp\\windowspatch.html"
        dest: "/tmp/{{ inventory_hostname }}_windowspatch.html"
        flat: yes
      delegate_to: "{{ inventory_hostname }}"

    - name: Attach a file to an request
      servicenow.servicenow.snow_record:
        username: "{{ snow_user }}"
        password: "{{ snow_password }}"
        instance: "{{ snow_id }}"
        state: present
        table: sc_req_item
        number: "{{ ritm }}"
        attachment: /tmp/{{ inventory_hostname }}_windowspatch.html
      delegate_to: localhost
      when: ritm is defined
      failed_when: false