- name: Start Services
  hosts: all
  gather_facts: no
  tasks:
    - name: Start Windows Service
      ansible.windows.win_service:
        name: "{{ service_name | default('W3SVC') }}"
        state: started