- name: Configure Windows Firewall
  hosts: all
  gather_facts: false
  tasks:

    - name: Configure Windows firewall
      ansible.windows.win_firewall:
        state: enabled
        profiles:
          - Domain
          - Public
          - Private
