- name: Enable Windows Firewall
  hosts: all
  gather_facts: false
  tasks:

    - name: Start firewall service
      ansible.windows.win_service:
        name: W3SVC
        state: started

    - name: Enable Windows firewall
      ansible.windows.win_firewall:
        state: enabled
        profiles:
          - Domain
          - Public
          - Private
