- name: Enable Windows Firewall
  hosts: all
  gather_facts: false
  tasks:

    - name: Enable Windows firewall
      ansible.windows.win_firewall:
        state: enabled
        profiles:
          - Domain
          - Public
          - Private
