---
- name: Chocolatey install multiple
  hosts: all
  gather_facts: false

  tasks:
    - name: Install specific versions of packages sequentially
      chocolatey.chocolatey.win_chocolatey:
        name: "{{ item }}"
        state: present
      loop: "{{ choco_packages }}"
