- name: Example Hashi Valt lookup
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Lookup secret from Hashi Valt
      ansible.builtin.debug:
        msg: "{{ lookup('community.hashi_vault.hashi_vault', 'secret/data/aap:READ_ME') }}"
      register: secret_output

    - name: Debug "Username
      ansible.builtin.debug:
        msg: "Username: {{ ansible_user }}"

    - name: Debug Password
      ansible.builtin.debug:
        msg: "Password: {{ ansible_password }}"
