- hosts: localhost
  gather_facts: false
  connection: local

  vars:
    linux_vms:
      - node: pve2
        name: database1
      - node: pve2
        name: web1
      - node: pve2
        name: web3
      - node: pve2
        name: web4
      - node: pve5
        name: testing

    windows_vms:
      - node: pve2
        name: win1
      - node: pve2
        name: win2
      - node: pve2
        name: win3
      - node: pve2
        name: win4
      - node: pve3
        name: dc1
  tasks:    
    
    - name: Manage Linux VMs
      community.proxmox.proxmox:
        api_user: root@pam
        api_password: "{{ lookup('env', 'PROXMOX_PASSWORD') }}"
        api_host: pve1.mackdev.net
        hostname: "{{ item.name }}"
        node: "{{ item.node }}"
        state: "{{ linux_vm_state | default('stopped') }}"
        timeout: 90
        force: true
      loop: "{{ linux_vms }}"
      loop_control:
        label: "{{ item.name }}"

    - name: Manage Windows VMs
      community.proxmox.proxmox_kvm:
        api_user: root@pam
        api_password: "{{ lookup('env', 'PROXMOX_PASSWORD') }}"
        api_host: pve1.mackdev.net
        name: "{{ item.name }}"
        node: "{{ item.node }}"
        state: "{{ windows_vm_state | default('stopped') }}"
        timeout: 90
      loop: "{{ windows_vms }}"
      loop_control:
        label: "{{ item.name }}"