---
- name: Update SNOW
  hosts: localhost
  gather_facts: no
  tasks:


    - name: Set variables
      set_fact:
        ritm: "{{ ansible_eda.event.payload.ritm }}"
      when: ansible_eda is defined

    - name: Update a Change Request
      servicenow.servicenow.snow_record:
        username: "{{ snow_user }}"
        password: "{{ snow_password }}"
        instance: "{{ snow_id }}"
        state: present
        table: sc_req_item
        number: "{{ ritm }}"
        data:
          comments: "{{ lookup('template','snow_success.j2') }}"
      delegate_to: localhost
      when: ritm is defined
